[project]
name = "gpt-5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "jupyterlab>=4.4.7",
    "openai>=1.107.1",
    "pandas>=2.3.2",
    "rich>=14.1.0",
]
