[project]
name = "nano-banana"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "google-genai>=1.35.0",
    "jupyterlab>=4.4.7",
    "pillow>=11.3.0",
    "rich>=14.1.0",
]
